---
apiVersion: v1
kind: Secret
metadata:
  name: node-1-bmc-secret
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=

---
apiVersion: midas.io/v1alpha1
kind: BareMetalAsset
metadata:
  name: node-1
spec:
  bmc:
    address: ipmi://192.168.111.1:6231
    credentialsName: node-1-bmc-secret
  bootMACAddress: "00:86:6a:bf:a9:14"
  hardwareProfile: "hardwareProfile"
  clusterDeployment:
    name: minikube
    namespace: default
